version: '2.3'

services:
  main:
    container_name: plant-dacon
    build:
      context: ./
      dockerfile: Dockerfile
    runtime: nvidia
    restart: always
    ports:
      - "9763:22"
      - "9762:6006"
      - "8888:8888"

    ipc: host
    stdin_open: true
    tty: true

